### ISSUE TITLE
what If the recognized noise samples are removed

### ISSUE THREAD

**Issue by wuyaoxuehun** [shengliu66/ELR#27]
Did you do any experiment if the recognized noise samples are removed, and train model with "clean" samples with CE loss?
if not, do you think this will work somehow?
Many thanks!

**Comment by shengliu66** [comment]
Hi

Nice idea, we tried, but the issue is that 1. this requires two times of training, 2. this would result in a very small dataset when the noise level is high. Empirically it always results in worse performance than other methods, but of course, better performance than CE perhaps especially when the noise level is low. 

Please let me know if you have other questions.

Sheng

**Comment by wuyaoxuehun** [comment]
> 

Thanks for your prompt reply!
